[build]
builder = "NIXPACKS"
buildCommand = "echo building!"

[deploy]
runtime = "UNSPECIFIED"
numReplicas = 1
startCommand = "gunicorn setup.wsgi.test_wsgi --log-file - && celery -A setup worker --pool=solo -l info"
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10