# Generated by Django 4.2.11 on 2024-05-05 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('powerhub', '0004_address_deliveryrecipient_remove_package_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuban', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=400)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerhub.queekabusiness')),
            ],
        ),
    ]
