# Generated by Django 4.2.11 on 2024-04-28 02:08

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=15, unique=True)),
                ('profile_image', models.ImageField(null=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('quantity', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('GR', 'Groceries'), ('CA', 'Clothing and Apparel'), ('EL', 'Electronics'), ('BM', 'Books and Media'), ('HBP', 'Health & Beauty Products'), ('HGF', 'Home Goods and Furniture'), ('TG', 'Toys and Games'), ('SOE', 'Sports and Outdoor Equipment'), ('PS', 'Pet Supplies'), ('OS', 'Office Supplies'), ('SFB', 'Specialty Foods and Beverages'), ('PMS', 'Pharmaceuticals and Medical Supplies'), ('APA', 'Automotive Parts and Accessories'), ('GF', 'Gifts and Flowers')], max_length=3)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('size', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('recipient_contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='QueekaBusiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('business_sn', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50, unique=True)),
                ('account_id', models.CharField(max_length=35, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='powerhub.queekabusiness')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_sn', models.CharField(max_length=5, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('delivery_service', models.CharField(choices=[('DHL', 'DHL'), ('GIGL', 'GIGL'), ('Kwik', 'Kwik'), ('RedStar', 'RedStar'), ('Glovo', 'Glovo'), ('Chowdeck', 'Chowdeck')], max_length=8)),
                ('type', models.CharField(choices=[('ED', 'Express'), ('NM', 'Normal')], max_length=2)),
                ('message', models.TextField()),
                ('package', models.ManyToManyField(related_name='items', to='powerhub.package')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerhub.queekabusiness')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_confirmation_code', models.IntegerField(unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
