# Generated by Django 4.2.11 on 2024-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('In-Transit', 'In-Transit'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
