# Generated by Django 4.0 on 2024-03-17 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0002_waitlist_alter_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business',
            new_name='QueekaBusiness',
        ),
    ]
