# Generated by Django 4.2.11 on 2024-05-03 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0002_order_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_sn', models.CharField(max_length=5, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('delivery_service', models.CharField(choices=[('DHL', 'DHL'), ('GIGL', 'GIGL'), ('Kwik', 'Kwik'), ('RedStar', 'RedStar'), ('Glovo', 'Glovo'), ('Chowdeck', 'Chowdeck')], max_length=8)),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('In-Transit', 'In-Transit'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('type', models.CharField(choices=[('ED', 'Express'), ('NM', 'Normal')], max_length=2)),
                ('message', models.TextField()),
                ('package', models.ManyToManyField(related_name='items', to='powerhub.package')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerhub.queekabusiness')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
