# Generated by Django 4.0 on 2024-03-17 01:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0003_rename_business_queekabusiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='queekabusiness',
            name='business_sn',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='queekabusiness',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
