# Generated by Django 4.2.11 on 2024-04-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0004_queekabusiness_business_sn_alter_queekabusiness_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_verified',
            field=models.BooleanField(default=False),
        ),
    ]
