# Generated by Django 4.2.11 on 2024-05-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0005_deliveryservice_packagedelivery_packagepickup_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualCard',
        ),
    ]
