# Generated by Django 4.2.11 on 2024-05-16 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0006_delete_virtualcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
