# Generated by Django 4.2.11 on 2024-04-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0007_remove_user_contact_verified_confirmationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationcode',
            name='generated_confirmation_code',
            field=models.IntegerField(unique=True),
        ),
    ]
