# Generated by Django 4.2.11 on 2024-04-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0009_package_alter_confirmationcode_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_service',
            field=models.CharField(choices=[('DHL', 'DHL'), ('GIGL', 'GIGL'), ('Kwik', 'Kwik'), ('RedStar', 'RedStar'), ('Glovo', 'Glovo'), ('Chowdeck', 'Chowdeck')], default=None, max_length=8),
            preserve_default=False,
        ),
    ]
