# Generated by Django 4.2.11 on 2024-04-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0011_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
