# Generated by Django 4.2.11 on 2024-05-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0012_alter_notification_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
    ]
