# Generated by Django 4.2.11 on 2024-05-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0016_notificationsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracking_id',
            field=models.CharField(max_length=7, null=True, unique=True),
        ),
    ]
