# Generated by Django 4.2.11 on 2024-05-21 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0017_shipment_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_status',
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CA', 'Courier Arrived'), ('PU', 'Picked Up'), ('EN', 'Enroute'), ('DL', 'Delayed'), ('DEL', 'Delivered'), ('CANC', 'Cancelled')], max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='powerhub.shipment')),
            ],
        ),
    ]
