# Generated by Django 4.2.11 on 2024-05-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0019_alter_shipmentstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentstatus',
            name='status',
            field=models.CharField(choices=[('PR', 'Processing'), ('CA', 'Courier Arrived'), ('PU', 'Picked Up'), ('EN', 'Enroute'), ('DL', 'Delayed'), ('DEL', 'Delivered'), ('CANC', 'Cancelled')], default='PR', max_length=4),
        ),
    ]
