# Generated by Django 4.2.11 on 2024-05-21 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0020_alter_shipmentstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerhub.deliveryservice'),
        ),
    ]
