# Generated by Django 4.2.11 on 2024-05-22 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0022_alter_deliveryservice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='delivery_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerhub.deliveryservice'),
        ),
    ]
