# Generated by Django 4.2.11 on 2024-05-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0023_alter_shipment_delivery_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
