# Generated by Django 4.2.11 on 2024-05-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0024_package_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='timeframe',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
