# Generated by Django 4.2.11 on 2024-05-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0034_remove_shipment_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentstatus',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='powerhub.shipment'),
        ),
    ]
