# Generated by Django 4.2.11 on 2024-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0035_shipmentstatus_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentstatus',
            name='shipment',
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.ManyToManyField(related_name='statuses', to='powerhub.shipmentstatus'),
        ),
    ]
