# Generated by Django 4.2.11 on 2024-05-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0036_remove_shipmentstatus_shipment_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='vehicle_type',
            field=models.CharField(choices=[('BIKE', 'BIKE'), ('CAR', 'CAR'), ('VAN', 'VAN'), ('TRUCK', 'TRUCK')], max_length=5, null=True),
        ),
    ]
