# Generated by Django 4.2.11 on 2024-06-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0039_rename_is_business_user_tier_1_user_tier_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagepickup',
            name='address',
        ),
        migrations.RemoveField(
            model_name='packagepickup',
            name='package',
        ),
        migrations.AddField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.DeleteModel(
            name='PackageDelivery',
        ),
        migrations.DeleteModel(
            name='PackagePickUp',
        ),
    ]
