# Generated by Django 4.2.11 on 2024-05-03 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0003_shipment_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('timeframe', models.DateTimeField()),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('timeframe', models.DateTimeField()),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='address',
        ),
        migrations.RemoveField(
            model_name='package',
            name='recipient_contact',
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_insured', models.BooleanField(default=False)),
                ('package_is_returnable', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerhub.address')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='pickup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='powerhub.address'),
        ),
    ]
