# Generated by Django 4.2.11 on 2024-05-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0014_notification_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
