# Generated by Django 4.2.11 on 2024-05-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0033_alter_shipment_shipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_status',
        ),
    ]
