# Generated by Django 4.2.11 on 2024-05-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0037_shipment_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Nigeria', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
