# Generated by Django 4.2.11 on 2024-06-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0038_address_city_address_country_address_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_business',
            new_name='tier_1',
        ),
        migrations.AddField(
            model_name='user',
            name='tier_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tier_3',
            field=models.BooleanField(default=False),
        ),
    ]
