# Generated by Django 4.2.11 on 2024-06-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhub', '0040_remove_packagepickup_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='recipient_contact',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
